# Generated by Django 3.1.2 on 2020-11-01 08:23

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(validators=[main_app.validators.time_validator]),
        ),
    ]
